baseURL = 'https://2b3d4f.github.io/mnml-demo'
languageCode = 'en-US'
title = 'mnml-demo'

[params]
showProposeEdit = true
proposeEditRepos = 'https://github.com/2b3d4f/mnml-demo'

[params.style]
fontFamily = '"Roboto Flex", "Noto Color Emoji", Helvetica, Arial, "Noto Sans", sans-serif'

[params.googleFonts]
path = "https://fonts.googleapis.com/css2?family=Noto+Color+Emoji&family=Roboto+Flex:opsz,wght@8..144,100..1000&display=swap"

[params.workaround]
deeplInputControllerMargin = true

[taxonomies]
tag = 'tags'

# category = 'categories'
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

# [[menus.main]]
# name = 'Categories'
# pageRef = '/categories'
# weight = 30

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[[module.imports]]
path = 'github.com/2b3d4f/mnml'
