baseURL = 'https://2b3d4f.github.io/mnml-demo'
languageCode = 'en-US'
title = 'mnml-demo'

[params.content]
showEditOn = true
editOnRepos = 'https://github.com/2b3d4f/mnml-demo'

[params.fonts]
fontFamily = '"Roboto Flex", "Noto Emoji", sans-serif'

[params.fonts.serif]
fontFamily = '"Roboto Serif", "Noto Emoji", serif'

[params.fonts.monospace]
fontFamily = '"Roboto Mono", "Noto Emoji", monospace'

[params.fonts.google]
url = "https://fonts.googleapis.com/css2?family=Noto+Emoji:wght@300..700&family=Roboto+Flex:opsz,wght@8..144,100..1000&family=Roboto+Mono:ital,wght@0,100..700;1,100..700&family=Roboto+Serif:ital,opsz,wght@0,8..144,100..900;1,8..144,100..900&display=swap"

[params.workaround]
deeplInputControllerMargin = true

[taxonomies]
tag = 'tags'

[permalinks]

[permalinks.page]
posts = '/posts/:slug/'

[permalinks.section]
posts = '/archives/'

# category = 'categories'
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

# [[menus.main]]
# name = 'Categories'
# pageRef = '/categories'
# weight = 30
[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40

[markup]

[markup.goldmark]

[markup.goldmark.parser]

[markup.goldmark.parser.attribute]
block = true

[markup.goldmark.renderer]
unsafe = true

[[module.imports]]
path = 'github.com/2b3d4f/mnml'
